name = "Bash"
language = "bash"
status = "alpha"
features = ["ast","uast","roles"]

[documentation]
description  = """
bash driver for [babelfish](https://github.com/bblfsh/bblfshd).
"""

[runtime]
os = "alpine"
go_version = "1.8"
native_version = ["8.131.11-r2"]
